version: '3'

services:
    react-website:
        build: .
        container_name: react-website
        command: npm run start
        volumes:
            - ./:/website
            - /website/node_modules
        ports:
            - "3000:3000"
        environment: 
            - NODE_ENV=development
